{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galyarder-design.fullname" . }}-data
  labels:
    {{- include "galyarder-design.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galyarder-design.fullname" . }}-config
  labels:
    {{- include "galyarder-design.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- with .Values.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
